---
- name: Add Firewall rules
  firewalld:
   port: 80/tcp
   permanent: true
   state: enabled

- name: Reload Firewall configuration for the new rule
  systemd:
   name: firewalld
   state: reloaded

- name: Copy indexfile to Apache directory
  copy:
   src: "{{ index_path  }}"
   dest: /var/www/html/index.html
